### PR TITLE
Travis

### PR DESCRIPTION
**Pull request by SimonWaldherr**
add [Continuous Integration](https://en.wikipedia.org/wiki/Continuous_integration) Test via [TravisCI](https://travis-ci.org/)

... see the full build log at <https://travis-ci.org/SimonWaldherr/Summarize-Flattr-Reports>

You have to create a free Account at [travis-ci.org](https://travis-ci.org/) (you can sign up via GitHub) and activate the repo at your profile page.
Please add/change the eMail-adress in the .travis.yml file.
From now on, every push will be tested on a linux vm at travis-ci.org.
Everytime the build status changes, you will get a eMail with the new state.

[Build Status](https://travis-ci.org/SimonWaldherr/Summarize-Flattr-Reports)

### CODE REVIEW

**Comment by katrinleinweber** [comment]
I'm not sure whether automated buildin/testing is necessary for a single R script. What is the advantage of CI vs. a running the script locally before each commit in order to find errors?

**Comment by SimonWaldherr** [comment]
the more tests, the better ;-)

it depends on how you define „necessary“. The benefit of a CI Server testing your changes is a much higher chance to detect errors.
The CI VM is always „clean“ and a local perfectly working version can fail on other systems because of missing data, packages, ... (eg. Issue [PR28](https://github.com/KonScience/Summarize-Flattr-Reports/pull/28)).
In other languages you can even check the test coverage, this means the percentage of lines tested via the CI test cases (eg. [the coverage of my golibs project](https://coveralls.io/github/SimonWaldherr/golibs)), i don’t know if this is possible in R too.
Also, you can make *tested* changes even when you have no locally installed R version (eg. smartphone).
An [extreme example of using CI services is my golibs repo](https://github.com/SimonWaldherr/golibs), on each commit it get’s tested on over 10 different Systems (including GNU/Linux, OS X, Windows Server 2012, MS Visual Studio (, a few releases ago even Microsoft Azure))
and additionally i use [Git-Hooks](http://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) (i put the [pre-commit hook file](https://github.com/SimonWaldherr/golibs/blob/master/pre-commit) also in the Repo.
And last but not least, it can also check all Pull Requests, so you know exactly if a PR will break the script or not.

**Comment by SimonWaldherr** [comment]
Have you thought about it again?
Are still some questions left unanswered?

What do you have to lose? 
It's free and they only want access to your public repos.

**Comment by katrinleinweber** [comment]
I don't think it's necessary, but I'll be curious to try it out in a week or two.

**Comment by SimonWaldherr** [comment]
ok, great, please ask if you have any questions

**Pull request merged**
